export const REQUEST_FILMS = 'REQUEST_FILMS'
export const RECEIVE_FILMS = 'RECEIVE_FILMS'
export const ERROR_FILMS   = 'ERROR_FILMS'

export const REQUEST_DELETE_FILM = 'REQUEST_DELETE_FILM'
export const SUCCESS_DELETE_FILM = 'SUCCESS_DELETE_FILM'
export const ERROR_DELETE_FILM   = 'ERROR_DELETE_FILM'

export const REQUEST_UPDATE_FILM = 'REQUEST_UPDATE_FILM'
export const SUCCESS_UPDATE_FILM = 'SUCCESS_UPDATE_FILM'
export const ERROR_UPDATE_FILM   = 'ERROR_UPDATE_FILM'